<?php

namespace App\DataFixtures;

use App\Entity\User;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class UsersFixtures extends Fixture
{
    public function load(ObjectManager $manager): void
    {
        $user = new User();
        $user->setPseudo('Corentin VÉROT');
        $user->setEmail('corentin.verot@outlook.com');
        $user->setPassword('123456789');
        $user->setRoles([
            "ROLE_ADMIN",
        ]);
        $manager->persist($user);

        $user = new User();
        $user->setPseudo('Nicolas MORIN');
        $user->setEmail('Nicolas.MORIN@etu.uca.fr');
        $user->setPassword('123456789');
        $user->setRoles([
            "ROLE_ADMIN",
        ]);
        $manager->persist($user);

        // Generated by https://www.fakenamegenerator.com/gen-random-fr-fr.php
        $user = new User();
        $user->setPseudo('Émile Barrière');
        $user->setEmail('EmileBarriere@jourrapide.com');
        $user->setPassword('ooH8shu6');
        $manager->persist($user);

        $user = new User();
        $user->setPseudo('Aubrey Trépanier');
        $user->setEmail('AubreyTrepanier@armyspy.com');
        $user->setPassword('Aigohgahkau5');
        $manager->persist($user);

        $user = new User();
        $user->setPseudo('Guillaume Faubert');
        $user->setEmail('GuillaumeFaubert@dayrep.com');
        $user->setPassword('re1rojaW');
        $manager->persist($user);

        $user = new User();
        $user->setPseudo('Hélène Carrière');
        $user->setEmail('HeleneCarriere@rhyta.com');
        $user->setPassword('mueRie4ew');
        $manager->persist($user);

        $manager->flush();
    }
}
